### ISSUE TITLE
global_i doesn't exist, see comment assert(global_i == 0); // Oops!

### ISSUE THREAD

**Issue by blockspacer** [apolukhin/Boost-Cookbook-4880OS#12]
global_i not declared

What `assert(global_i == 0); // Oops!` means?

See https://github.com/apolukhin/Boost-Cookbook/blob/912e36f38b9b1da93b03ae7afd19fcec0900aa83/Chapter05/02_mutex/main.cpp#L40

**Comment by apolukhin** [comment]
Thanks for the report! It should be `shared_i `

Fixed in the sources
