### ISSUE TITLE
error: DSO missing from command line  libpthread.so.0

### ISSUE THREAD

**Issue by sildeag** [apolukhin/Boost-Cookbook-4880OS#5]
Any ideas?

**Comment by apolukhin** [comment]
In what recipe did you find that bug? What compiler and OS are you using?

**Comment by sildeag** [comment]
Thank you for responding.  I opened the project `BoostBook.pro` using `Qt Creator 4.5.2` based on `Qt 5.9.5.`  The messages were generated in Chapter01 `any`.  I tried `g++ version 7.3`, `g++ version 8.2`, and `clang version 6.0`.  I was going to look more closely at which versions of `libpthread.so` were on my `Ubuntu 18.04` `linux` system.

**Comment by sildeag** [comment]
I tried opening and running `any.pro` and some of the other individual projects and they all ran perfectly.  As I haven't used Qt Creator that much, I had thought it might have been setup so that running `BoostBook.pro` was possible.  I think it might be possible using Qt `.pri` files.   It appears from `http://doc.qt.io/qt-5/qmake-advanced-usage.html` that for example an `any.pri` might include `any.commands` where `.commands` are used for for generating output from the input.  @apolukhin you may close these issues as I was obviously doing something not intended.  Closed issue #3 may be helpful to other Ubuntu users.

**Comment by apolukhin** [comment]
Anyway, thanks for the report! And thanks for your interest! :)
